Implemented Responsiveness, Mapping Data to PieChart and Total
EndavaCollab/fe_expenses_manager pull request #10
Opened 2023-10-12 14:40 UTC by Mihaidaniel22

2023-10-13 09:40 UTC, en-teodora-velicu requested changes

2023-10-13 09:40 UTC, en-teodora-velicu commented on src/components/homepage/CustomPieChart.jsx
> +    const fetchData = async () => {
This should be in a service

2023-10-13 09:40 UTC, en-teodora-velicu commented on src/components/homepage/CustomPieChart.jsx
> +      if (key === "Food & Restaurants")
This is better with a switch case and also extract it in a new function

2023-10-13 09:40 UTC, en-teodora-velicu commented on src/components/homepage/DateNavigation.jsx
> +              views={["day", "month", "year"]}
this is an array of constants. move outside the component

2023-10-13 09:40 UTC, en-teodora-velicu commented on src/components/homepage/TotalExpenses.jsx
> +    const fetchData = async () => {
Extract in a service for expenses

2023-10-13 09:40 UTC, en-teodora-velicu commented on src/services/categories-service.jsx
> +    // const response = await apiClient().get("http://localhost:8080/expense/category", {
remove commented code

2023-10-13 09:40 UTC, en-teodora-velicu commented on src/services/total-service.jsx
> +export const getTotal = async () => {
total service? you should create you services having in mind a broader scope. total what? total expenses? categories what? expense categories chart? you can have a service expenses.js(for all info regarding costs) reports.js(the endpoints used to create the reports page)

2023-10-18 09:56 UTC, en-teodora-velicu approved these changes

2023-10-18 09:56 UTC, CristiStroescu approved these changes

2023-10-18 09:57 UTC, Alexandra18042003 approved these changes

2023-10-18 10:04 UTC, merged