Implemented ReportsPage components
EndavaCollab/fe_expenses_manager pull request #9
Opened 2023-10-12 14:39 UTC by Mihaidaniel22

2023-10-13 09:34 UTC, en-teodora-velicu requested changes

2023-10-13 09:34 UTC, en-teodora-velicu commented on src/components/homepage/DateNavigation.jsx
> +              views={["day", "month", "year"]}
this array can be extracted as a const outside of the function.

2023-10-13 09:34 UTC, en-teodora-velicu commented on src/components/reports/Categories.jsx
> +        <Typography className="category-title">Food & Restaurants</Typography>
This is duplicated code. A box can be set as a reusable component SimpleCard (or sth like that) and you will send title and total as params

2023-10-13 09:34 UTC, en-teodora-velicu commented on src/components/reports/ReportsNavigation.jsx
> +            <DateCalendar
The calendar should be a reusable component. Try and optimize it to fit our needs

2023-10-13 09:34 UTC, en-teodora-velicu commented on src/components/reports/ReportsPieChart.jsx
> +import React from "react";
We should have a reusable component for pie charts. Please update for both homepage and reports. Try to adapt the props to fit our needs

2023-10-13 09:34 UTC, en-teodora-velicu commented on src/components/reports/ReportsPieChart.jsx
> +const ReportsPieChart = () => {
Same thing here. Reports should be a reusable comp

2023-10-18 09:56 UTC, en-teodora-velicu approved these changes

2023-10-18 09:57 UTC, CristiStroescu approved these changes

2023-10-18 09:57 UTC, merged